import { ReactNode } from "react";
import { LicenseItem } from "../licenses/utils";

interface LicenseColumnInterface {
  label: string;
  key: string;
  render?: (item: LicenseItem) => ReactNode;
}

export const licenseColumn: LicenseColumnInterface[] = [
  {
    label: "Key",
    key: "key",
    render: (item: LicenseItem) => <span>{item.key}</span>,
  },
  { label: "Creation Date", key: "created_on" },
  { label: "Generated By", key: "generated_by" },
  { label: "Duration", key: "duration" },
  { label: "Note", key: "note" },
  { label: "Used On", key: "used_on" },
  { label: "Expires On", key: "expires_on" },
  { label: "Status", key: "status" },
  { label: "IP", key: "ip" },
  { label: "HWID", key: "hwid" },
];

export default licenseColumn;
export type { LicenseColumnInterface };
